### ISSUE TITLE
World Inventories

### ISSUE THREAD

**Issue by BootheBoys** [poggit-orphanage/WorldProtect#10]
Hey, I see you have gamemode inventories (which seem to be working inconsistently), but I think World Inventories would be better and more useful for a lot of people. I.E. if your in the hub world, you have a specific inventory, and if you go into a different world, your inventory is specific to that world. Sorry if I am putting this at the wrong place, I am new here and I don't really know where to put feature requests..

**Comment by supercrafter333** [comment]
**Is this issue still there?** 

If not, please close the issue. 
If so, please post a comment on this issue. 

If you don't respond within the next 7 days, the issue will be closed.

**Comment by supercrafter333** [comment]
Closed due to inactivity.
