### ISSUE TITLE
Gamemode delayed

### ISSUE THREAD

**Issue by AiminProjects** [poggit-orphanage/WorldProtect#14]
When i set the gamemode it's delayed (e.g., when you go to a creative-gamemode world the gamemode won't be changed unless you go to another world. I use Aternos PocketMine 3.15 with some plugin installed that maybe cause the bug: Festival, MultiWorld, and Worlds

**Comment by AimanIlyasM** [comment]
for specific things, i use aternos pocketmine 3.15 with plugin installed that maybe cause bug: Festival, MultiWorld, Worlds

**Comment by Atara6431** [comment]
this function is one of the main use of this plugin, but nobody fix it.today i still can't use gamemode change
