### ISSUE TITLE
Border Feature doesn't works+

### ISSUE THREAD

**Issue by Ju999** [poggit-orphanage/WorldProtect#18]
I tried to set a border with the command  **/worldprotect lobby3 border 321 381 175 149**, and there was a message "Border for lobby3 set to  (...)-(...)" but when i tried to walk through it just worked normally.
Also when i restarted and removed op, it didnt worked.
pls fix

**Comment by supercrafter333** [comment]
**Is this error still there?** 

If not, please close the issue. 
If so, please post a comment on this issue. 

If you don't respond within the next 7 days, the issue will be closed.
