### ISSUE TITLE
Server Crashed after /wp add {Player} || Crashdump

### ISSUE THREAD

**Issue by ghost** [poggit-orphanage/WorldProtect#23]
[19:45:38.655] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Server::getPlayer()" (EXCEPTION) in "plugins/WorldProtect_dev-39.phar/src/aliuly/worldprotect/WpProtectMgr" at line 76

--- Stack trace ---

#0 plugins/WorldProtect_dev-39.phar/src/aliuly/worldprotect/common/SubCommandMap(48): aliuly\worldprotect\WpProtectMgr->onSCommand(object ipad54\netherblocks\player\Player#98672, object pocketmine\command\PluginCommand#23889, string[3] add, string[19] Dragon's Apocalypse, array[1])

#1 plugins/WorldProtect_dev-39.phar/src/aliuly/worldprotect/common/BasicPlugin(123): aliuly\worldprotect\common\SubCommandMap

**Comment by SOF3** [comment]
@supercrafter333 ^

**Comment by supercrafter333** [comment]
Hmmm.... I've forgot this 😂

**Comment by supercrafter333** [comment]
Fixed (#24)
