### ISSUE TITLE
Crash on /wp banitem

### ISSUE THREAD

**Issue by usser1976** [poggit-orphanage/WorldProtect#31]
Altay Crash Dump Fri Nov 18 21:02:59 CET 2022

Altay version: 4.10.9 [Protocol 557]
Git commit: 0000000000000000000000000000000000000000
PHP version: 8.0.24
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: WorldProtect

Error: Call to a member function getId() on null
File: plugins/WorldProtect_dev-46.phar/src/aliuly/worldprotect/BanItem
Line: 79
Type: Error
Backtrace:
#0 plugins/WorldProtect_dev-46.phar/src/aliuly/worldprotect/common/SubCommandMap(48): aliuly\worldprotect\BanItem->onSCommand(object ipad54\netherblocks\player\Player#149528, int 0, string[7] banitem, string[8] Farmwelt, array[1])
#1 plugins/WorldProtect_dev-46.phar/src/aliuly/worldprotect/common/BasicPlugin(116): aliuly\worldprotect\common\SubCommandMap->dispatchSCmd(object ipad54\netherblocks\player\Player#149528, object pocketmine\command\PluginCommand#28033, array[1], string[8] Farmwelt)
#2 plugins/WorldProtect_dev-46.phar/src/aliuly/worldprotect/Main(225): aliuly\worldprotect\common\BasicPlugin->dispatchSCmd(object ipad54\netherblocks\player\Player#149528, object pocketmine\command\PluginCommand#28033, array[2], string[8] Farmwelt)
#3 pmsrc/src/command/PluginCommand(50): aliuly\worldprotect\Main->onCommand(object ipad54\netherblocks\player\Player#149528, object pocketmine\command\PluginCommand#28033, string[2] wp, array[2])
#4 pmsrc/src/command/SimpleCommandMap(211): pocketmine\command\PluginCommand->execute(object ipad54\netherblocks\player\Player#149528, string[2] wp, array[2])
#5 pmsrc/src/Server(1498): pocketmine\command\SimpleCommandMap->dispatch(object ipad54\netherblocks\player\Player#149528, string[13] wp banitem 15)
#6 pmsrc/src/player/Player(1438): pocketmine\Server->dispatchCommand(object ipad54\netherblocks\player\Player#149528, string[13] wp banitem 15)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(754): pocketmine\player\Player->chat(string[14] /wp banitem 15)
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#173090)
#9 pmsrc/src/network/mcpe/NetworkSession(410): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#201387)
#10 pmsrc/src/network/mcpe/NetworkSession(373): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#173090, string[35] M./wp banitem 15..Jd.........D.C...)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[39] S...//PHJ..,I.U04e8..2.e...w...q.......)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 1, string[48] . .#v...........`./....=.=..cH?(vO...G...Pz...}.)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#117903)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/src/Server(1757): pocketmine\snooze\SleeperHandler->sleepUntil(float 1668801779.1205)
#17 pmsrc/src/Server(1105): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[10] /home/slg/, string[18] /home/slg/plugins/)
#19 pmsrc/src/PocketMine(328): pocketmine\server()
#20 pmsrc(11): require(string[54] phar:///home/slg/PocketMine-MP.phar/src/PocketMine.php)

Code:
[70] 				if (isset($ids[$item->getId()])) {
[71] 					unset($ids[$item->getId()]);
[72] 					++$cc;
[73] 				}
[74] 			}
[75] 		} elseif ($scmd == "banitem") {
[76] 			foreach ($args as $i) {
[77] 				$item = StringToItemParser::getInstance()->parse($i);
[78] 				if ($item instanceof Item && isset($ids[$item->getId()])) continue;
[79] 				$ids[$item->getId()] = ItemName::str($item);
[80] 				++$cc;
[81] 			}
[82] 		} else {
[83] 			return false;
[84] 		}
[85] 		if (!$cc) {
[86] 			$c->sendMessage(mc::_("No items updated"));
[87] 			return true;
[88] 		}
[89] 		if (count($ids)) {

**Comment by supercrafter333** [comment]
Please use PocketMine-MP. Forks aren't supported.
