### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SillierShark195** [poggit-orphanage/WorldProtect#36]
Why its says | u not allowed to do this

**Comment by supercrafter333** [comment]
If you've protected a world and trying to build or do something disallowed, you'll get these message.

**Comment by SillierShark195** [comment]
> If you've protected a world and trying to build or do something disallowed, you'll get these message.

Its command https://youtu.be/7Fs_zWLp3CY

**Comment by scamaccas** [comment]
> Why its says | u not allowed to do this

i get this problem too how to fix it?

**Comment by SillierShark195** [comment]
> > Why its says | u not allowed to do this
> 
> i get this problem too how to fix it?

Idk
