### ISSUE TITLE
update plugin

### ISSUE THREAD

**Issue by CoolCuzzy** [poggit-orphanage/WorldProtect#37]
Update to new api. soz not sure what its called but i really enjoy using this plugin since it works well with multiworld. also not sure if im able to suggest things here but maybe you can add toggle for fire spread and lava flow for worlds?

**Comment by supercrafter333** [comment]
This plugin have a very old code(-style).
I'm not planning to update this plugin for PM5.

I'm planning to create a new and better plugin as a replacement for WorldProtect.

**Comment by Atara6431** [comment]
I'm glad to hear that, there's no good world plugin in PM5, I won't update to PM5 unless you release a brand new version!
With lofty blessings

**Comment by supercrafter333** [comment]
This plugin is no longer under developed. It's outdated and no longer maintained by poggit-orphanage!
### Please use [WorldDefend](https://github.com/Taylor-pm-pl/WorldDefend) by [@Taylor-pm-pl](https://github.com/Taylor-pm-pl)
