### ISSUE TITLE
Commands not working properly.

### ISSUE THREAD

**Issue by JUSTaMod** [poggit-orphanage/WorldProtect#4]
Using -- PocketMine-MP version 3.0.4
And -- WorldProtect v2.3.6 (latest dev branch build)

Having an issue with commands that require the world name as the second argument. (Such as /wp noexplode, or /wp border... etc.)

It tells me the syntax is "_/worldprotect [world] noexplode [off|world|spawn]_", but it will not except the world name as the sub command - "_Unknown sub-command worldnamehere (try /worldprotect help)_".

I've tried a bunch of different syntax's but to no avail.
I'm not sure whats causing this, if I did I'd take a stab at fixing it.

Let me know if there's is a fix for this, or if I'm just using the commands wrong.

**Comment by Awzaw** [comment]
<img width="551" alt="screen shot 2018-07-05 at 15 37 31" src="https://user-images.githubusercontent.com/10437212/42308833-62ce8db8-8069-11e8-8c85-9e329b73da49.png">

Works fine for me - are you sure that you didn't rename your world folders without updating level.dat?

**Comment by JUSTaMod** [comment]
Ah. My mistake.

The world name was also split into two letters which I condensed. -Not sure if that could cause any issues.

Either way, thanks!
