### ISSUE TITLE
Border range issues.

### ISSUE THREAD

**Issue by ZandercraftGames** [poggit-orphanage/WorldProtect#9]
I have tried everything about range. I have tried `/wp HG-01 border range`, I have tried `/wp HG-01 border range 50`, I have tried `/wp HG-01 border range 50 50`.
Both `/wp HG-01 border range 50` and `/wp HG-01 border range 50 50` result in a message saying my usage is wrong the that the usage of the command is `worldprotect [world] border [range:none:x1 z1 x2 z2]`
And `/wp HG-01 border range` results in a message saying `[WP] Border for HG-01 removed`.
If I understand correctly, the border range command is supposed to "define the border as being range blocks in x and z axis away from the spawn point." but the only command it seems to accept where it actually does something is just `/wp HG-01 border range` in which case it clears the border. Am I just being stupid, or does this command not function at all?

**Comment by Awzaw** [comment]
Agreed that the docs are badly written... you need to replace the word 'range' with an integer value:

`/wp HG-01 border 50`

if you type 

`/wp HG-01 border range`

it's probably setting the border to 0 as you didn't actually define 'range'.

**Comment by jennocool** [comment]
Does the border command even do anything I van Just Walk past it
